package ccs.com.vhr.mapper;

import ccs.com.vhr.model.Adjustsalary;

public interface AdjustsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insert(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insertSelective(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    Adjustsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKeySelective(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKey(Adjustsalary record);
}