package ccs.com.vhr.mapper;

import ccs.com.vhr.model.Appraise;

public interface AppraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insert(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insertSelective(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    Appraise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKeySelective(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKey(Appraise record);
}