package ccs.com.vhr.mapper;

import ccs.com.vhr.model.Employeeremove;

public interface EmployeeremoveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insert(Employeeremove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insertSelective(Employeeremove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    Employeeremove selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKeySelective(Employeeremove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeremove
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKey(Employeeremove record);
}