package ccs.com.vhr.mapper;

import ccs.com.vhr.model.Empsalary;

public interface EmpsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insert(Empsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insertSelective(Empsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    Empsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKeySelective(Empsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empsalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKey(Empsalary record);
}