package ccs.com.vhr.mapper;

import ccs.com.vhr.model.MailSendLog;

public interface MailSendLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_send_log
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insert(MailSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_send_log
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insertSelective(MailSendLog record);
}