package ccs.com.vhr.mapper;

import ccs.com.vhr.model.MenuRole;

public interface MenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insert(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int insertSelective(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    MenuRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKeySelective(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    int updateByPrimaryKey(MenuRole record);

    void deleteByRid(Integer rid);
}