package ccs.com.vhr.model;

import java.util.Date;

public class Adjustsalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.asDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Date asdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.beforeSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer beforesalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.afterSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer aftersalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.reason
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.remark
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.id
     *
     * @return the value of adjustsalary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.id
     *
     * @param id the value for adjustsalary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.eid
     *
     * @return the value of adjustsalary.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.eid
     *
     * @param eid the value for adjustsalary.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.asDate
     *
     * @return the value of adjustsalary.asDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Date getAsdate() {
        return asdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.asDate
     *
     * @param asdate the value for adjustsalary.asDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAsdate(Date asdate) {
        this.asdate = asdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.beforeSalary
     *
     * @return the value of adjustsalary.beforeSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getBeforesalary() {
        return beforesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.beforeSalary
     *
     * @param beforesalary the value for adjustsalary.beforeSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setBeforesalary(Integer beforesalary) {
        this.beforesalary = beforesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.afterSalary
     *
     * @return the value of adjustsalary.afterSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getAftersalary() {
        return aftersalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.afterSalary
     *
     * @param aftersalary the value for adjustsalary.afterSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAftersalary(Integer aftersalary) {
        this.aftersalary = aftersalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.reason
     *
     * @return the value of adjustsalary.reason
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.reason
     *
     * @param reason the value for adjustsalary.reason
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.remark
     *
     * @return the value of adjustsalary.remark
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.remark
     *
     * @param remark the value for adjustsalary.remark
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}