package ccs.com.vhr.model;

import java.util.Date;

public class Appraise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.appDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Date appdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.appResult
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String appresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.appContent
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String appcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.remark
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.id
     *
     * @return the value of appraise.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.id
     *
     * @param id the value for appraise.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.eid
     *
     * @return the value of appraise.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.eid
     *
     * @param eid the value for appraise.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.appDate
     *
     * @return the value of appraise.appDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Date getAppdate() {
        return appdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.appDate
     *
     * @param appdate the value for appraise.appDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAppdate(Date appdate) {
        this.appdate = appdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.appResult
     *
     * @return the value of appraise.appResult
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getAppresult() {
        return appresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.appResult
     *
     * @param appresult the value for appraise.appResult
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAppresult(String appresult) {
        this.appresult = appresult == null ? null : appresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.appContent
     *
     * @return the value of appraise.appContent
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getAppcontent() {
        return appcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.appContent
     *
     * @param appcontent the value for appraise.appContent
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAppcontent(String appcontent) {
        this.appcontent = appcontent == null ? null : appcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.remark
     *
     * @return the value of appraise.remark
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.remark
     *
     * @param remark the value for appraise.remark
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}