package ccs.com.vhr.model;

public class Empsalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empsalary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empsalary.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empsalary.sid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empsalary.id
     *
     * @return the value of empsalary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empsalary.id
     *
     * @param id the value for empsalary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empsalary.eid
     *
     * @return the value of empsalary.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empsalary.eid
     *
     * @param eid the value for empsalary.eid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empsalary.sid
     *
     * @return the value of empsalary.sid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empsalary.sid
     *
     * @param sid the value for empsalary.sid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}