package ccs.com.vhr.model;

import java.util.Date;

public class MailSendLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.msgId
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.empId
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer empid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.status
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.routeKey
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String routekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.exchange
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String exchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.count
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.tryTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Date trytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.createTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_log.updateTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.msgId
     *
     * @return the value of mail_send_log.msgId
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.msgId
     *
     * @param msgid the value for mail_send_log.msgId
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.empId
     *
     * @return the value of mail_send_log.empId
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.empId
     *
     * @param empid the value for mail_send_log.empId
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.status
     *
     * @return the value of mail_send_log.status
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.status
     *
     * @param status the value for mail_send_log.status
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.routeKey
     *
     * @return the value of mail_send_log.routeKey
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getRoutekey() {
        return routekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.routeKey
     *
     * @param routekey the value for mail_send_log.routeKey
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setRoutekey(String routekey) {
        this.routekey = routekey == null ? null : routekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.exchange
     *
     * @return the value of mail_send_log.exchange
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.exchange
     *
     * @param exchange the value for mail_send_log.exchange
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.count
     *
     * @return the value of mail_send_log.count
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.count
     *
     * @param count the value for mail_send_log.count
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.tryTime
     *
     * @return the value of mail_send_log.tryTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Date getTrytime() {
        return trytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.tryTime
     *
     * @param trytime the value for mail_send_log.tryTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setTrytime(Date trytime) {
        this.trytime = trytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.createTime
     *
     * @return the value of mail_send_log.createTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.createTime
     *
     * @param createtime the value for mail_send_log.createTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_log.updateTime
     *
     * @return the value of mail_send_log.updateTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_log.updateTime
     *
     * @param updatetime the value for mail_send_log.updateTime
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}