package ccs.com.vhr.model;

import java.util.Date;

public class OpLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.addDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Date adddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.operate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String operate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.hrid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer hrid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.id
     *
     * @return the value of oplog.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.id
     *
     * @param id the value for oplog.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.addDate
     *
     * @return the value of oplog.addDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Date getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.addDate
     *
     * @param adddate the value for oplog.addDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAdddate(Date adddate) {
        this.adddate = adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.operate
     *
     * @return the value of oplog.operate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.operate
     *
     * @param operate the value for oplog.operate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setOperate(String operate) {
        this.operate = operate == null ? null : operate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.hrid
     *
     * @return the value of oplog.hrid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getHrid() {
        return hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.hrid
     *
     * @param hrid the value for oplog.hrid
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setHrid(Integer hrid) {
        this.hrid = hrid;
    }
}