package ccs.com.vhr.model;

import java.util.Date;

public class Salary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.basicSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer basicsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.bonus
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer bonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.lunchSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer lunchsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.trafficSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer trafficsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.allSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer allsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.pensionBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer pensionbase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.pensionPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Float pensionper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.createDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.medicalBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer medicalbase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.medicalPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Float medicalper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.accumulationFundBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Integer accumulationfundbase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.accumulationFundPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private Float accumulationfundper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.name
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.id
     *
     * @return the value of salary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.id
     *
     * @param id the value for salary.id
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.basicSalary
     *
     * @return the value of salary.basicSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getBasicsalary() {
        return basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.basicSalary
     *
     * @param basicsalary the value for salary.basicSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setBasicsalary(Integer basicsalary) {
        this.basicsalary = basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.bonus
     *
     * @return the value of salary.bonus
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.bonus
     *
     * @param bonus the value for salary.bonus
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.lunchSalary
     *
     * @return the value of salary.lunchSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getLunchsalary() {
        return lunchsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.lunchSalary
     *
     * @param lunchsalary the value for salary.lunchSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setLunchsalary(Integer lunchsalary) {
        this.lunchsalary = lunchsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.trafficSalary
     *
     * @return the value of salary.trafficSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getTrafficsalary() {
        return trafficsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.trafficSalary
     *
     * @param trafficsalary the value for salary.trafficSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setTrafficsalary(Integer trafficsalary) {
        this.trafficsalary = trafficsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.allSalary
     *
     * @return the value of salary.allSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getAllsalary() {
        return allsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.allSalary
     *
     * @param allsalary the value for salary.allSalary
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAllsalary(Integer allsalary) {
        this.allsalary = allsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.pensionBase
     *
     * @return the value of salary.pensionBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getPensionbase() {
        return pensionbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.pensionBase
     *
     * @param pensionbase the value for salary.pensionBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setPensionbase(Integer pensionbase) {
        this.pensionbase = pensionbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.pensionPer
     *
     * @return the value of salary.pensionPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Float getPensionper() {
        return pensionper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.pensionPer
     *
     * @param pensionper the value for salary.pensionPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setPensionper(Float pensionper) {
        this.pensionper = pensionper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.createDate
     *
     * @return the value of salary.createDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.createDate
     *
     * @param createdate the value for salary.createDate
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.medicalBase
     *
     * @return the value of salary.medicalBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getMedicalbase() {
        return medicalbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.medicalBase
     *
     * @param medicalbase the value for salary.medicalBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setMedicalbase(Integer medicalbase) {
        this.medicalbase = medicalbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.medicalPer
     *
     * @return the value of salary.medicalPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Float getMedicalper() {
        return medicalper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.medicalPer
     *
     * @param medicalper the value for salary.medicalPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setMedicalper(Float medicalper) {
        this.medicalper = medicalper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.accumulationFundBase
     *
     * @return the value of salary.accumulationFundBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Integer getAccumulationfundbase() {
        return accumulationfundbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.accumulationFundBase
     *
     * @param accumulationfundbase the value for salary.accumulationFundBase
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAccumulationfundbase(Integer accumulationfundbase) {
        this.accumulationfundbase = accumulationfundbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.accumulationFundPer
     *
     * @return the value of salary.accumulationFundPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public Float getAccumulationfundper() {
        return accumulationfundper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.accumulationFundPer
     *
     * @param accumulationfundper the value for salary.accumulationFundPer
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setAccumulationfundper(Float accumulationfundper) {
        this.accumulationfundper = accumulationfundper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.name
     *
     * @return the value of salary.name
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.name
     *
     * @param name the value for salary.name
     *
     * @mbggenerated Thu Nov 05 10:03:24 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}